# -*- coding:utf-8 -*-
#    author    :   丁雪峰
#    time      :   2014-12-08 11:39:11
#    email     :   fengidri@yeah.net
#    version   :   1.0.1

EventNames=[ 
        "BufNewFile"		,
        "BufReadPre"		,
        "BufRead"		,
        "BufReadPost"		,
        "BufReadCmd"		,
        "FileReadPre"		,
        "FileReadPost"		,
        "FileReadCmd"		,
        "FilterReadPre"		,
        "FilterReadPost"	,
        "StdinReadPre"		,
        "StdinReadPost"		,
        "BufWrite"		,
        "BufWritePre"		,
        "BufWritePost"		,
        "BufWriteCmd"		,
        "FileWritePre"		,
        "FileWritePost"		,
        "FileWriteCmd"		,
        "FileAppendPre"		,
        "FileAppendPost"	,
        "FileAppendCmd"		,
        "FilterWritePre"	,
        "FilterWritePost"	,
        "BufAdd"		,
        "BufCreate"		,
        "BufDelete"		,
        "BufWipeout"		,
        "BufFilePre"		,
        "BufFilePost"		,
        "BufEnter"		,
        "BufLeave"		,
        "BufWinEnter"		,
        "BufWinLeave"		,
        "BufUnload"		,
        "BufHidden"		,
        "BufNew"		,
        "SwapExists"		,
        "FileType"		,
        "Syntax"		,
        "EncodingChanged"	,
        "TermChanged"		,
        "VimEnter"		,
        "GUIEnter"		,
        "GUIFailed"		,
        "TermResponse"		,
        "QuitPre"		,
        "VimLeavePre"		,
        "VimLeave"		,
        "FileChangedShell"	,
        "FileChangedShellPost"	,
        "FileChangedRO"		,
        "ShellCmdPost"		,
        "ShellFilterPost"	,
        "FuncUndefined"		,
        "SpellFileMissing"	,
        "SourcePre"		,
        "SourceCmd"		,
        "VimResized"		,
        "FocusGained"		,
        "FocusLost"		,
        "CursorHold"		,
        "CursorHoldI"		,
        "CursorMoved"		,
        "CursorMovedI"		,
        "WinEnter"		,
        "WinLeave"		,
        "TabEnter"		,
        "TabLeave"		,
        "CmdwinEnter"		,
        "CmdwinLeave"		,
        "InsertEnter"		,
        "InsertChange"		,
        "InsertLeave"		,
        "InsertCharPre"		,
        "ColorScheme"		,
        "RemoteReply"		,
        "QuickFixCmdPre"	,
        "QuickFixCmdPost"	,
        "SessionLoadPost"	,
        "MenuPopup"		,
        "CompleteDone"		,
        "User"			,
        ]

if __name__ == "__main__":
    pass

